### ISSUE TITLE
add functionality to store the name of the user

### ISSUE THREAD

**Issue by antgad** [SEProjGrp5/slash#8]

**Comment by antgad** [comment]
closed with the following commit: https://github.com/SEProjGrp5/slash/commit/44bdf041593e4d5112e7f354127369bb400a5145

**Comment by AnmolikaGoyal** [comment]
**Discussion Summary :** Since our future scope includes ordering and purchase, it is ideal to store user information. Hence we need to add functionality to store the name of the user
